version: '3.7'

networks:
  xnat-services:
    name: &networkname xnat-services
    driver: overlay
    attachable: true

services:
  xnat-web:
    build:
      context: ./xnat
      args:
        XNAT_VERSION: ${XNAT_VERSION}
        XNAT_SMTP_ENABLED: ${XNAT_SMTP_ENABLED}
        XNAT_SMTP_HOSTNAME: ${XNAT_SMTP_HOSTNAME}
        XNAT_SMTP_PORT: ${XNAT_SMTP_PORT}
        XNAT_SMTP_AUTH: ${XNAT_SMTP_AUTH}
        XNAT_SMTP_USERNAME: ${XNAT_SMTP_USERNAME}
        XNAT_SMTP_PASSWORD: ${XNAT_SMTP_PASSWORD}
        XNAT_DATASOURCE_DRIVER: ${XNAT_DATASOURCE_DRIVER}
        XNAT_DATASOURCE_URL: ${XNAT_DATASOURCE_URL}
        XNAT_DATASOURCE_USERNAME: ${XNAT_DATASOURCE_USERNAME}
        XNAT_DATASOURCE_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
        TOMCAT_XNAT_FOLDER: ${TOMCAT_XNAT_FOLDER}
        XNAT_ROOT: ${XNAT_ROOT}
        XNAT_HOME: ${XNAT_HOME}
        XNAT_EMAIL: ${XNAT_EMAIL}
    ports:
      - 8104:8104
    volumes:
      - ./xnat/plugins:${XNAT_HOME}/plugins
      - ./xnat-data/home/logs:${XNAT_HOME}/logs
      - ./xnat-data/home/work:${XNAT_HOME}/work
      - ./xnat-data/archive:${XNAT_ROOT}/archive
      - ./xnat-data/prearchive:${XNAT_ROOT}/prearchive
      - ./xnat-data/build:${XNAT_ROOT}/build
      - ./xnat-data/cache:${XNAT_ROOT}/cache
      - ./xnat-data/workspaces:${XNAT_ROOT}/workspaces
      - ./xnat-data/ftp:${XNAT_ROOT}/ftp
      - ./xnat-data/pipeline:${XNAT_ROOT}/pipeline
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP} -Xmx${XNAT_MAX_HEAP} -Dxnat.home=${XNAT_HOME}
      - XNAT_HOME=${XNAT_HOME}
      - XNAT_ROOT=${XNAT_ROOT}
      - TOMCAT_USER_ID=${TOMCAT_UID}
      - TOMCAT_GROUP_ID=${TOMCAT_GID}
    networks:
      - xnat-services

  xnat-db:
    image: postgres:${PG_VERSION}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      #
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${XNAT_DATASOURCE_ADMIN_PASSWORD}
      - POSTGRES_DB=${XNAT_DATASOURCE_NAME}
      # variables for the sql script
      - XNAT_DATASOURCE_USERNAME=${XNAT_DATASOURCE_USERNAME}
      - XNAT_DATASOURCE_PASSWORD=${XNAT_DATASOURCE_PASSWORD}
    networks:
      - xnat-services

  xnat-nginx:
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - xnat-services
    depends_on:
      - xnat-web
      - jupyterhub

  jupyterhub:
    image: xnat/jupyterhub:1.0.0
    hostname: jupyterhub
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    networks:
      - xnat-services
    environment:
      JH_NETWORK: *networkname
      JH_UID: "${JH_UID}"
      JH_GID: "${JH_GID}"
      NB_UID: "${NB_UID}"
      NB_GID: "${NB_GID}"
      JH_XNAT_URL: "${JH_XNAT_URL}"
      JH_XNAT_SERVICE_TOKEN: "${JH_XNAT_SERVICE_TOKEN}"
      JH_XNAT_USERNAME: "${JH_XNAT_USERNAME}"
      JH_XNAT_PASSWORD: "${JH_XNAT_PASSWORD}"
